### ISSUE TITLE
Error groovy.lang.MissingPropertyException: No such property: mailService for class: grails.plugins.postmark.MapBuilder

### ISSUE THREAD

**Issue by semurat** [digerata/grails-postmark#4]
I have tried sending a mail using sendmail with this plugin and spring-security-ui as follows:

sendMail {
  to user.email
  from conf.ui.forgotPassword.emailFrom
  subject conf.ui.forgotPassword.emailSubject
  body(view: "/mailer/password-recover", model: [user: user, url:url])
}

But it failed with the error that you can read in subject.
It worked when the mailService in MapBuilder class was change by postmarkService and injected there. 
also included this line in PostmarkService:

Map sendPostmarkMail(Closure callable) {
  def messageBuilder = new MapBuilder()
  messageBuilder.postmarkService = this
....
I'm not sure if it's a bug or I have not known how to fix it

**Comment by digerata** [comment]
What class are you calling sendMail from?  It sounds like the mailService isn't being injected into whichever class you are calling sendMail from.  By default, it only injects into controllers and services, I believe.

-Mike

**Comment by semurat** [comment]
I extend this class from spring-security-ui plugin grails.plugins.springsecurity.ui.RegisterController.
and rewrite forgotPassword action.

I've just seen that mailService is injected in that controller and the block of code where invokes sendMail is:

def conf = SpringSecurityUtils.securityConfig
def body = conf.ui.forgotPassword.emailBody
if (body.contains('$')) {
body = evaluate(body, [user: user, url: url])
}
mailService.sendMail {
to user.email
from conf.ui.forgotPassword.emailFrom
subject conf.ui.forgotPassword.emailSubject
html body.toString()
}

The new class that extends the original has this code:

def conf = SpringSecurityUtils.securityConfig

sendMail {
to user.email
from conf.ui.forgotPassword.emailFrom
subject conf.ui.forgotPassword.emailSubject
body(view: "/mailer/password-recover", model: [user: user, url:url])
}

I hope you can see what's the problem i have ;)

**Comment by mattgrommes** [comment]
I'm having this same problem. I have a controller where I just call sendMail with a 'body' like semrat does and it fails with the same error. I'm just learning Groovy so I'm afraid I can't say much more than that.

**Comment by semurat** [comment]
I'm not an expert in Groovy, so I'm not sure my solution was fine...but it works for me.

The problem is that rewriting the code of the plugin is only in my working copy, so the Team has the original plugin and fails when they try to send emails.

**Comment by digerata** [comment]
Matt, is it the same problem where you are using it with spring-security?

**Comment by mattgrommes** [comment]
I am using spring-security but not spring-security-ui. I don't have anything specifically using spring-security on this method but it's used in the controller elsewhere.

**Comment by karumuru** [comment]
Hey Guys, I am having same problem of what @mattgrommes is facing.Could anyone please provide the solution if u guys have fixed it

**Comment by jerrydboonstra** [comment]
Same problem here when upgrading from Grails 1.3.7 to Grails 2.2.1.  Upgraded Mail plugin from 0.9 to 1.0.1, still no love.

**Comment by jerrydboonstra** [comment]
i have a workaround that works for me.  In Bootstrap, add

```
     import grails.plugins.postmark.MapBuilder
```

and

```
    def mailService
    def groovyPagesTemplateEngine
```

to get a handle to the injected dependencies, then in Bootstrap init closure, add:

```
    mailService.metaClass.groovyPagesTemplateEngine = groovyPagesTemplateEngine
    MapBuilder.metaClass.mailService = mailService;
```
